from enum import Enum

class RobotState(Enum):
    BOOTING = "BOOTING"
    READY = "READY"
    PAIRING = "PAIRING"
    CONNECTED = "CONNECTED"
    FORWARD = "FORWARD"
    BACKWARD = "BACKWARD"
    TURN_LEFT = "TURN_LEFT"
    TURN_RIGHT = "TURN_RIGHT"
    STOPPED = "STOPPED"
    PERSON_DETECTED = "PERSON_DETECTED"
    SAFETY_STOP = "SAFETY_STOP"
    CAMERA_ERROR = "CAMERA_ERROR"
    MOTOR_ERROR = "MOTOR_ERROR"
    SYSTEM_ERROR = "SYSTEM_ERROR"
    DISCONNECTED = "DISCONNECTED"
    SHUTTING_DOWN = "SHUTTING_DOWN"

class SafetyState(Enum):
    CLEAR = "CLEAR"
    PERSON_DETECTED = "PERSON_DETECTED"
    SAFETY_STOP = "SAFETY_STOP"
    ERROR_STOP = "ERROR_STOP"

class MovementCommand(Enum):
    FORWARD = "FORWARD"
    BACKWARD = "BACKWARD"
    TURN_LEFT = "TURN_LEFT"
    TURN_RIGHT = "TURN_RIGHT"
    STOP = "STOP"
    EMERGENCY_STOP = "EMERGENCY_STOP"
